version: 2.1

jobs:
  terraform_init:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init

workflows:
  version: 2
  Init-Plan:
    jobs:
      - terraform_init
