version: 2.1

jobs:
  terraform_init:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init

  terraform_output:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Terraform Output
          command:  |
            case "$ENV" in 
            #case 1 
            "dev") terraform apply -var="region=${ENV}" --auto-approve;; 
      
            #case 2 
            "prod") terraform apply -var="region=${ENV}" --auto-approve;; 
      
            #case 3 
            "qa") terraform apply -var="region=${ENV}" --auto-approve;; 
            esac 

workflows:
  version: 2 
  Init-Plan:
    jobs:
      - terraform_init
      - terraform_output :
          requires : 
            - terraform_init
