version: 2.1

jobs:
  terraform_init:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init

  terraform_output:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Terraform Output
          command: 
            terraform apply -var-file="${ENV}.tfvars" --auto-approve

workflows:
  version: 2 
  Init-Apply-Output:
    jobs:
      - terraform_init
      - terraform_output :
          requires : 
            - terraform_init
          filters:
             branches:
                only: main
