version: 2.1

jobs:
  terraform_init:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init

  terraform_output:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Terraform Output
          command:  read -p "Variable1=" variable1

workflows:
  version: 2
  Init-Plan:
    jobs:
      - terraform_init
      - terraform_output :
          requires : 
            - terraform_init
