version: 2.1

jobs:
  terraform_init:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
  
  terraform_plan:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Terraform Plan
          command: terraform plan

  terraform_output:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
        name : Deploying
        command : |
          echo "Please enter the required input:"
          read -p "REGION:" var_region
          name: Terraform Plan
          command: terraform output -var="regoion=${var_region}"

workflows:
  version: 2
  Init-Plan:
    jobs:
      - terraform_init

      - terraform_output:
            requires: 
              - terraform_init